source 'https://rubygems.org'

gem 'nokogiri', '1.10.8'
gem 'rspec'
gem 'simplecov'
gem 'codeclimate-test-reporter'
gem 'selenium-webdriver'
gem 'mysql2'
gem 'capybara'
gem 'poltergeist'
gem 'whenever'
